using BeatSaberMarkupLanguage.Attributes;
using BeatSaberMarkupLanguage.ViewControllers;


namespace CustomFloorPlugin.UI {


    /// <summary>
    /// A <see cref="BSMLAutomaticViewController"/> generated by Zenject and maintained by BSML at runtime.<br/>
    /// BSML uses the <see cref="ViewDefinitionAttribute"/> to determine the Layout of the GameObjects and their Components<br/>
    /// Tagged functions and variables from this class may be used/called by BSML if the .bsml file mentions them.<br/>
    /// </summary>
    [ViewDefinition("CustomFloorPlugin.Views.Changelog.bsml")]
    internal class ChangelogView : BSMLAutomaticViewController {

        [UIValue("changelog-text")]
        public string Changelog => 
    @"<size=150%><color=#888888>Version 6.0.0</color></size>
    - Basicly a complete rewrite of the Plugin and updated for 1.13.2
       It now uses Zenject, thank you so much Auros for making SiraUtil <3
    - CustomPlatforms can now be used in the menu
    - Redesigned menu, moved settings section here and added a changelog
    - Removed Environment Override Setting because it's implemented in 
       the base game itself";
    }
}
