using BeatSaberMarkupLanguage.Attributes;
using BeatSaberMarkupLanguage.ViewControllers;


namespace CustomFloorPlugin.UI {


    /// <summary>
    /// A <see cref="BSMLAutomaticViewController"/> generated by Zenject and maintained by BSML at runtime.<br/>
    /// BSML uses the <see cref="ViewDefinitionAttribute"/> to determine the Layout of the GameObjects and their Components<br/>
    /// Tagged functions and variables from this class may be used/called by BSML if the .bsml file mentions them.<br/>
    /// </summary>
    [ViewDefinition("CustomFloorPlugin.Views.Changelog.bsml")]
    internal class ChangelogView : BSMLAutomaticViewController {

        [UIValue("changelog-text")]
        public string Changelog =>
        @"<size=150%><color=#888888>Version 6.0.0</color></size>
        - Basicly a complete rewrite of the Plugin and updated for 1.13.2
        - CustomPlatforms can now be used in the menu
        - Redesigned menu, moved settings section here and added a changelog
        - Removed Environment Override Setting because it's implemented in 
           the base game itself
        - Added LightEffects in Multiplayer
        - Removed BS Utils as a dependency
        - Drasticly simplified CustomScripts";

        [UIValue("credits-text")]
        public string Credits =>
        @"<size=150%><color=#888888>Credits</color></size>
        - Huge shoutout to boulders2000, thank you so much for all the testing
        - Thanks to Auros for making SiraUtil (Zenject <3)
        - everyone in #pc-mod-dev, thanks for all the help";
    }
}
