using System.Collections.Generic;

using BeatSaberMarkupLanguage.Attributes;
using BeatSaberMarkupLanguage.Components;
using BeatSaberMarkupLanguage.ViewControllers;

using CustomFloorPlugin.Configuration;

using HMUI;

using Zenject;


namespace CustomFloorPlugin.UI
{
    /// <summary>
    /// A <see cref="BSMLAutomaticViewController"/> generated by Zenject and maintained by BSML at runtime.<br/>
    /// BSML uses the <see cref="ViewDefinitionAttribute"/> to determine the Layout of the GameObjects and their Components<br/>
    /// Tagged functions and variables from this class may be used/called by BSML if the .bsml file mentions them.<br/>
    /// </summary>
    [ViewDefinition("CustomFloorPlugin.Views.PlatformLists.bsml")]
    [HotReload(RelativePathToLayout = "CustomFloorPlugin/Views/PlatformLists.bsml")]
    internal class PlatformListsView : BSMLAutomaticViewController
    {
        private PluginConfig? _config;
        private PlatformManager? _platformManager;
        private PlatformSpawner? _platformSpawner;

        private Dictionary<CustomPlatform, CustomListTableData.CustomCellInfo>? _platformCellPairs;

        /// <summary>
        /// The table of currently loaded Platforms for singleplayer
        /// </summary>
        [UIComponent("singleplayer-platforms-list")]
        private readonly CustomListTableData? _singleplayerPlatformListTable = null;

        /// <summary>
        /// The table of currently loaded Platforms for multiplayer
        /// </summary>
        [UIComponent("multiplayer-platforms-list")]
        private readonly CustomListTableData? _multiplayerPlatformListTable = null;

        /// <summary>
        /// The table of currently loaded Platforms for multiplayer
        /// </summary>
        [UIComponent("a360-platforms-list")]
        private readonly CustomListTableData? _a360PlatformListTable = null;

        /// <summary>
        /// An <see cref="System.Array"/> of all <see cref="CustomListTableData"/>s
        /// </summary>
        private CustomListTableData[]? _allListTables;

        /// <summary>
        /// Indicates whether the loading symbol should be shown or not
        /// </summary>
        [UIValue("loading-indicator-active")]
        public bool LoadingIndicatorActive
        {
            get => _loadingIndicatorActive;
            set
            {
                _loadingIndicatorActive = value;
                NotifyPropertyChanged();
            }
        }
        private bool _loadingIndicatorActive = true;

        [Inject]
        public void Construct(PluginConfig config, PlatformSpawner platformSpawner, PlatformManager platformManager)
        {
            _config = config;
            _platformManager = platformManager;
            _platformSpawner = platformSpawner;
            _platformCellPairs = new Dictionary<CustomPlatform, CustomListTableData.CustomCellInfo>();
        }

        [UIAction("select-cell")]
        // ReSharper disable once UnusedMember.Local
        // ReSharper disable once UnusedParameter.Local
        private async void TabSelect(SegmentedControl segmentedControl, int _1)
        {
            await _platformManager!.PlatformsLoadingTask!;
            PlatformType type = (PlatformType)segmentedControl.selectedCellNumber;
            int index = _platformManager.GetIndexForType(type);
            await _platformSpawner!.ChangeToPlatformAsync(index);
            _allListTables![segmentedControl.selectedCellNumber].tableView.ScrollToCellWithIdx(index, TableView.ScrollPositionType.Center, true);
            _allListTables![segmentedControl.selectedCellNumber].tableView.SelectCellWithIdx(index);
            _platformManager.CurrentPlatformType = type;
        }

        /// <summary>
        /// Called when a <see cref="CustomPlatform"/> is selected by the user<br/>
        /// </summary>
        /// <param name="_">I love how optimised BSML is</param>
        /// <param name="idx">Cell index of the users selection</param>
        [UIAction("singleplayer-select")]
        // ReSharper disable once UnusedMember.Local
        // ReSharper disable once UnusedParameter.Local
        private async void SingleplayerSelect(TableView _, int idx)
        {
            await _platformSpawner!.SetPlatformAndShowAsync(idx, PlatformType.Singleplayer);
        }

        /// <summary>
        /// Called when a <see cref="CustomPlatform"/> is selected by the user<br/>
        /// </summary>
        /// <param name="_">I love how optimised BSML is</param>
        /// <param name="idx">Cell index of the users selection</param>
        [UIAction("multiplayer-select")]
        // ReSharper disable once UnusedMember.Local
        // ReSharper disable once UnusedParameter.Local
        private async void MultiplayerSelect(TableView _, int idx)
        {
            await _platformSpawner!.SetPlatformAndShowAsync(idx, PlatformType.Multiplayer);
        }

        /// <summary>
        /// Called when a <see cref="CustomPlatform"/> is selected by the user<br/>
        /// </summary>
        /// <param name="_">I love how optimised BSML is</param>
        /// <param name="idx">Cell index of the users selection</param>
        [UIAction("a360-select")]
        // ReSharper disable once UnusedMember.Local
        // ReSharper disable once UnusedParameter.Local
        private async void A360Select(TableView _, int idx)
        {
            await _platformSpawner!.SetPlatformAndShowAsync(idx, PlatformType.A360);
        }

        /// <summary>
        /// Changing to the current platform when the menu is shown<br/>
        /// [Called by Beat Saber]
        /// </summary>
        protected override async void DidActivate(bool firstActivation, bool addedToHierarchy, bool screenSystemEnabling)
        {
            base.DidActivate(firstActivation, addedToHierarchy, screenSystemEnabling);
            await _platformManager!.PlatformsLoadingTask!;
            int platformIndex = _platformManager.GetIndexForType(_platformManager.CurrentPlatformType);
            await _platformSpawner!.ChangeToPlatformAsync(platformIndex);
        }

        /// <summary>
        /// Swapping back to the standard menu environment or to the selected singleplayer platform<br/>
        /// when the menu is closed<br/>
        /// [Called by Beat Saber]
        /// </summary>
        protected override async void DidDeactivate(bool removedFromHierarchy, bool screenSystemDisabling)
        {
            base.DidDeactivate(removedFromHierarchy, screenSystemDisabling);
            await _platformManager!.PlatformsLoadingTask!;
            int platformIndex = 0;
            if (_config!.ShowInMenu)
                platformIndex = _config.ShufflePlatforms
                    ? _platformSpawner!.RandomPlatformIndex
                    : _platformManager!.GetIndexForType(PlatformType.Singleplayer);
            await _platformSpawner!.ChangeToPlatformAsync(platformIndex);
        }

        /// <summary>
        /// (Re-)Loading the tables for the ListView of available platforms<br/>
        /// [Called by BSML]
        /// </summary>
        [UIAction("#post-parse")]
        // ReSharper disable once UnusedMember.Local
        private async void PostParse()
        {
            await _platformManager!.PlatformsLoadingTask!;
            _platformManager.PlatformsLoadingTask.Result.Sort(1, _platformManager.PlatformsLoadingTask.Result.Count - 1, null);
            _allListTables = new[] { _singleplayerPlatformListTable!, _multiplayerPlatformListTable!, _a360PlatformListTable! };
            LoadingIndicatorActive = false;
            foreach (CustomPlatform platform in _platformManager.PlatformsLoadingTask.Result)
                AddCellForPlatform(platform, false);
            for (int i = 0; i < _allListTables.Length; i++)
            {
                _allListTables[i].tableView.ReloadData();
                int idx = _platformManager.GetIndexForType((PlatformType)i);
                _allListTables[i].tableView.ScrollToCellWithIdx(idx, TableView.ScrollPositionType.Center, true);
                _allListTables[i].tableView.SelectCellWithIdx(idx);
            }
        }

        internal void AddCellForPlatform(CustomPlatform platform, bool forceReload)
        {
            if (_allListTables == null) return;
            CustomListTableData.CustomCellInfo cell = new(platform.platName, platform.platAuthor, platform.icon);
            _platformCellPairs!.Add(platform, cell);
            foreach (CustomListTableData listTable in _allListTables)
            {
                listTable.data.Add(cell);
                if (forceReload)
                    listTable.tableView.ReloadData();
            }
        }

        internal void RemoveCellForPlatform(CustomPlatform platform)
        {
            if (_allListTables == null) return;
            CustomListTableData.CustomCellInfo cell = _platformCellPairs![platform];
            for (int i = 0; i < _allListTables.Length; i++)
            {
                _allListTables[i].data.Remove(cell);
                _allListTables[i].tableView.ReloadData();
                if (_platformManager!.GetIndexForType((PlatformType)i) == _platformManager!.PlatformsLoadingTask!.Result.IndexOf(platform))
                {
                    _allListTables[i].tableView.SelectCellWithIdx(0);
                    _allListTables[i].tableView.ScrollToCellWithIdx(0, TableView.ScrollPositionType.Center, true);
                }
            }
        }
    }
}