using System;
using System.Collections.Generic;
using System.Collections.Specialized;

using BeatSaberMarkupLanguage.Attributes;
using BeatSaberMarkupLanguage.Components;
using BeatSaberMarkupLanguage.ViewControllers;

using CustomFloorPlugin.Configuration;
using CustomFloorPlugin.Helpers;

using HMUI;

using IPA.Utilities;

using Zenject;


namespace CustomFloorPlugin.UI
{
    /// <summary>
    /// A <see cref="BSMLAutomaticViewController"/> generated by Zenject and maintained by BSML at runtime.<br/>
    /// BSML uses the <see cref="ViewDefinitionAttribute"/> to determine the Layout of the GameObjects and their Components<br/>
    /// Tagged functions and variables from this class may be used/called by BSML if the .bsml file mentions them.<br/>
    /// </summary>
    [ViewDefinition("CustomFloorPlugin.Views.PlatformLists.bsml")]
    [HotReload(RelativePathToLayout = "CustomFloorPlugin/Views/PlatformLists.bsml")]
    internal class PlatformListsView : BSMLAutomaticViewController, IInitializable, IDisposable
    {
        private PluginConfig? _config;
        private AssetLoader? _assetLoader;
        private PlatformManager? _platformManager;
        private PlatformSpawner? _platformSpawner;

        [UIComponent("singleplayer-platforms-list")]
        private readonly CustomListTableData? _singleplayerPlatformListTable = null;

        [UIComponent("multiplayer-platforms-list")]
        private readonly CustomListTableData? _multiplayerPlatformListTable = null;

        [UIComponent("a360-platforms-list")]
        private readonly CustomListTableData? _a360PlatformListTable = null;

        private readonly CustomCellComparer _customCellComparer = new();

        private CustomListTableData[]? _listTables;
        private ScrollView[]? _scrollViews;
        private PlatformType _selectedPlatformType;

        [Inject]
        public void Construct(PluginConfig config, AssetLoader assetLoader, PlatformSpawner platformSpawner, PlatformManager platformManager)
        {
            _config = config;
            _assetLoader = assetLoader;
            _platformManager = platformManager;
            _platformSpawner = platformSpawner;
        }

        public void Initialize()
        {
            _platformManager!.AllPlatforms.CollectionChanged += OnCollectionDidChange;
        }

        public void Dispose()
        {
            _platformManager!.AllPlatforms.CollectionChanged -= OnCollectionDidChange;
        }

        [UIAction("select-cell")]
        // ReSharper disable once UnusedMember.Local
        // ReSharper disable once UnusedParameter.Local
        private void TabSelect(SegmentedControl segmentedControl, int _1)
        {
            _selectedPlatformType = (PlatformType)segmentedControl.selectedCellNumber;
            int index = _platformManager!.GetIndexForType(_selectedPlatformType);
            _listTables![segmentedControl.selectedCellNumber].tableView.ScrollToCellWithIdx(index, TableView.ScrollPositionType.Beginning, false);
            _listTables![segmentedControl.selectedCellNumber].tableView.SelectCellWithIdx(index, true);
        }

        /// <summary>
        /// Called when a <see cref="CustomPlatform"/> is selected by the user
        /// </summary>
        /// <param name="_1">I love how optimised BSML is</param>
        /// <param name="index">Cell index of the users selection</param>
        [UIAction("platform-select")]
        // ReSharper disable once UnusedMember.Local
        // ReSharper disable once UnusedParameter.Local
        private void PlatformSelect(TableView _1, int index)
        {
            _ = _platformSpawner!.SetPlatformAndShowAsync(index, _selectedPlatformType);
        }

        /// <summary>
        /// Changing to the current platform when the menu is shown<br/>
        /// [Called by Beat Saber]
        /// </summary>
        protected override void DidActivate(bool firstActivation, bool addedToHierarchy, bool screenSystemEnabling)
        {
            base.DidActivate(firstActivation, addedToHierarchy, screenSystemEnabling);
            int platformIndex = _platformManager!.GetIndexForType(_selectedPlatformType);
            _ = _platformSpawner!.ChangeToPlatformAsync(platformIndex);
        }

        /// <summary>
        /// Swapping back to the standard menu environment or to the selected singleplayer platform<br/>
        /// when the menu is closed<br/>
        /// [Called by Beat Saber]
        /// </summary>
        protected override void DidDeactivate(bool removedFromHierarchy, bool screenSystemDisabling)
        {
            base.DidDeactivate(removedFromHierarchy, screenSystemDisabling);
            int index = 0;
            if (_config!.ShowInMenu)
                index = _config.ShufflePlatforms
                    ? _platformSpawner!.RandomPlatformIndex
                    : _platformManager!.GetIndexForType(PlatformType.Singleplayer);
            _ = _platformSpawner!.ChangeToPlatformAsync(index);
        }

        /// <summary>
        /// (Re-)Loading the tables for the ListView of available platforms<br/>
        /// [Called by BSML]
        /// </summary>
        [UIAction("#post-parse")]
        // ReSharper disable once UnusedMember.Local
        private void PostParse()
        {
            _listTables = new[] { _singleplayerPlatformListTable!, _multiplayerPlatformListTable!, _a360PlatformListTable! };
            _scrollViews = new ScrollView[_listTables.Length];
            foreach (CustomPlatform platform in _platformManager!.AllPlatforms)
                AddCellForPlatform(platform);
            for (int i = 0; i < _listTables.Length; i++)
            {
                int idx = _platformManager!.GetIndexForType((PlatformType)i);
                _listTables[i].tableView.ReloadData();
                _listTables[i].tableView.ScrollToCellWithIdx(idx, TableView.ScrollPositionType.Beginning, false);
                _listTables[i].tableView.SelectCellWithIdx(idx);
                _scrollViews[i] = _listTables[i].tableView.GetField<ScrollView, TableView>("_scrollView");
            }
        }

        private void OnCollectionDidChange(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (_listTables == null) return;
            switch (e.Action)
            {
                case NotifyCollectionChangedAction.Add:
                    foreach (CustomPlatform platform in e.NewItems)
                        AddCellForPlatform(platform);
                    RefreshListViews();
                    break;
                case NotifyCollectionChangedAction.Remove:
                    foreach (CustomPlatform platform in e.OldItems)
                        RemoveCellForPlatform(platform);
                    RefreshListViews();
                    break;
            }
        }

        private void RefreshListViews()
        {
            for (int i = 0; i < _listTables!.Length; i++)
            {
                float pos = _scrollViews![i].GetField<float, ScrollView>("_destinationPos");
                _listTables[i].tableView.ReloadData();
                _scrollViews[i].ScrollTo(pos, false);
            }
        }

        private void AddCellForPlatform(CustomPlatform platform)
        {
            if (_listTables == null) return;
            CustomListTableData.CustomCellInfo cell = new(platform.platName, platform.platAuthor, platform.icon ? platform.icon : _assetLoader!.FallbackCover);
            foreach (CustomListTableData listTable in _listTables)
                listTable.data.AddSorted(1, listTable.data.Count - 1, cell, _customCellComparer);
        }

        private void RemoveCellForPlatform(CustomPlatform platform)
        {
            if (_listTables == null) return;
            int platformIndex = _platformManager!.AllPlatforms.IndexOf(platform);
            for (int i = 0; i < _listTables.Length; i++)
            {
                _listTables[i].data.RemoveAt(platformIndex);
                if (_platformManager!.GetIndexForType((PlatformType)i) == platformIndex)
                {
                    _listTables[i].tableView.SelectCellWithIdx(0);
                    _listTables[i].tableView.ScrollToCellWithIdx(0, TableView.ScrollPositionType.Beginning, false);
                }
            }
        }

        private class CustomCellComparer : IComparer<CustomListTableData.CustomCellInfo>
        {
            public int Compare(CustomListTableData.CustomCellInfo x, CustomListTableData.CustomCellInfo y)
            {
                if (x == y) return 0;
                int textComparison = string.CompareOrdinal(x.text, y.text);
                if (textComparison != 0) return textComparison;
                int subtextComparison = string.CompareOrdinal(x.subtext, y.subtext);
                return subtextComparison;
            }
        }
    }
}